# Generated by Django 6.0.2 on 2026-02-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('total_price', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'naqd'), ('click', 'CLICK orqali'), ('payme', 'PAYME orqali'), ('cart', 'Karta orqali'), ('other', 'boshqa tolov turlari orqali')], max_length=50)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('waiting', 'Kutulmoqda'), ('in_pogress', 'Hali jarayonda'), ('waiting payment', 'Tolov qilishni kutmoqda'), ('delivering', 'Yetkazib berish jarayonida'), ('delivered', 'Yetkazib berilgan'), ('complited', 'Jarayon Yakunlangan'), ('cancelled by customer', 'Xaridor tomonidan Bekor qilingan'), ('cancelled by seller', 'Sotuvchi tomonidan Bekor qilingan')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
