# Generated by Django 6.0.2 on 2026-02-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Naqd'), ('click', 'CLICK orqali'), ('payme', 'PAYME orqali'), ('cart', 'Karta orqali'), ('other', 'Boshqa')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('waiting', 'Kutulmoqda'), ('in_progress', 'Jarayonda'), ('waiting_payment', 'Tolovni kutmoqda'), ('delivering', 'Yetkazilmoqda'), ('delivered', 'Yetkazildi'), ('completed', 'Yakunlandi'), ('cancelled_by_customer', 'Xaridor bekor qildi'), ('cancelled_by_seller', 'Sotuvchi bekor qildi')], default='new', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.userorder')),
            ],
        ),
        migrations.DeleteModel(
            name='UserItems',
        ),
    ]
